### ISSUE TITLE
Starring the project

### ISSUE THREAD

**Issue by mfld-fr** [skipperbent/happn-php-sdk#5]
Help this project by starring it, including the owner, that seems to have forgotten to do such :-)

**Comment by skipperbent** [comment]
Sorry on behalf of the owner - he's stupid and forgetful.

Great work by the way; i'm really busy with the simple-router project at the moment, so it's great to see other people contributing  👍  you officially earned yourself 1.000.000 internet-points :)

**Comment by mfld-fr** [comment]
1 million points for a little contribution ? Whoaaah.... let me close this one and submit another contribution to try to earn 1 billion now :-D !

**Comment by skipperbent** [comment]
Hahaha 👍  Yeah you better watch out, soon all those hot internet-ladies are gonna be all over you, like you're some kind of new Justin Bieber.. don't tell me I didn't warn you haha :D 

Thanks for the contribution though, really appreciate it!
